name: Create PR from master to develop

on:
  push:
    branches:
      - main

jobs:
  raise-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: create pull request
        run: gh pr create -B develop -H main --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

