name: Create PR from master to develop

on:
  push:
    branches:
      - main

jobs:
  raise-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3.11.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Merge master into develop"
          base: "develop"
          title: "Merge master into develop"
          body: "This pull request merges changes from the master branch into the develop branch."
