name: Create PR from master to develop

on:
  push:
    branches:
      - main

jobs:
  raise-pr:
    runs-on: ubuntu-latest
    env:
       GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Set Git config
        run: |
          git config --local user.email "vanaparthy.rajkumar@gmail.com"
          git config --local user.name "tesla1729"
      - name: Merge main back to develop
        run: |
          git fetch --unshallow
          git checkout develop
          git pull
          git merge --no-ff ${{ github.base_ref }} -m "Auto-merge master/main back to develop"
          git push --force
        env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

